export const Interests = [
    { value: "1", label: "Shoes" },
    { value: "2", label: "T-shirts" },
    { value: "3", label: "Jeans" },
    { value: "4", label: "Watches" },
    { value: "5", label: "Bags" },
    { value: "6", label: "Sunglasses" },
    { value: "7", label: "Caps" },
    { value: "8", label: "Jackets" },
    { value: "9", label: "Sweaters" },
    { value: "10", label: "Scarves" },
    { value: "11", label: "Belts" },
    { value: "12", label: "Hoodies" },
    { value: "13", label: "Shorts" },
    { value: "14", label: "Skirts" },
    { value: "15", label: "Dresses" },
    { value: "16", label: "Suits" },
    { value: "17", label: "Coats" },
    { value: "18", label: "Gloves" },
    { value: "19", label: "Sandals" },
    { value: "20", label: "Boots" },
    { value: "21", label: "Heels" },
    { value: "22", label: "Slippers" },
    { value: "23", label: "Formal Shoes" },
    { value: "24", label: "Sneakers" },
    { value: "25", label: "Backpacks" },
    { value: "26", label: "Laptop Bags" },
    { value: "27", label: "Gym Bags" },
    { value: "28", label: "Travel Bags" },
    { value: "29", label: "Jewelry" },
    { value: "30", label: "Rings" },
    { value: "31", label: "Earrings" },
    { value: "32", label: "Necklaces" },
    { value: "33", label: "Bracelets" },
    { value: "34", label: "Anklets" },
    { value: "35", label: "Makeup" },
    { value: "36", label: "Skincare" },
    { value: "37", label: "Perfumes" },
    { value: "38", label: "Hair Care" },
    { value: "39", label: "Socks" },
    { value: "40", label: "Ties" },
    { value: "41", label: "Underwear" },
    { value: "42", label: "Swimwear" },
    { value: "43", label: "Sleepwear" },
    { value: "44", label: "Sportswear" },
    { value: "45", label: "Fitness Equipment" },
    { value: "46", label: "Yoga Mats" },
    { value: "47", label: "Towels" },
    { value: "48", label: "Mugs" },
    { value: "49", label: "Water Bottles" },
    { value: "50", label: "Kitchenware" },
    { value: "51", label: "Cookware" },
    { value: "52", label: "Dining Sets" },
    { value: "53", label: "Cutlery" },
    { value: "54", label: "Decor Items" },
    { value: "55", label: "Wall Art" },
    { value: "56", label: "Cushions" },
    { value: "57", label: "Bed Linen" },
    { value: "58", label: "Curtains" },
    { value: "59", label: "Lighting" },
    { value: "60", label: "Candles" },
    { value: "61", label: "Stationery" },
    { value: "62", label: "Notebooks" },
    { value: "63", label: "Pens" },
    { value: "64", label: "Pencils" },
    { value: "65", label: "Markers" },
    { value: "66", label: "Paint Supplies" },
    { value: "67", label: "Toys" },
    { value: "68", label: "Board Games" },
    { value: "69", label: "Puzzles" },
    { value: "70", label: "Action Figures" },
    { value: "71", label: "Dolls" },
    { value: "72", label: "Video Games" },
    { value: "73", label: "Gaming Accessories" },
    { value: "74", label: "Headphones" },
    { value: "75", label: "Speakers" },
    { value: "76", label: "Mobile Covers" },
    { value: "77", label: "Chargers" },
    { value: "78", label: "Power Banks" },
    { value: "79", label: "Tablets" },
    { value: "80", label: "Laptops" },
    { value: "81", label: "Desktop Computers" },
    { value: "82", label: "Monitors" },
    { value: "83", label: "Printers" },
    { value: "84", label: "Smartwatches" },
    { value: "85", label: "Fitness Trackers" },
    { value: "86", label: "Camera Gear" },
    { value: "87", label: "Lenses" },
    { value: "88", label: "Tripods" },
    { value: "89", label: "Memory Cards" },
    { value: "90", label: "External Drives" },
    { value: "91", label: "Books" },
    { value: "92", label: "E-books" },
    { value: "93", label: "Magazines" },
    { value: "94", label: "Craft Supplies" },
    { value: "95", label: "DIY Kits" },
    { value: "96", label: "Pet Supplies" },
    { value: "97", label: "Aquariums" },
    { value: "98", label: "Plants" },
    { value: "99", label: "Gardening Tools" },
    { value: "100", label: "Outdoor Gear" }
  ];
  